[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

# 2015

[[bin]]
name = "2015-day1"
path = "src/2015/day1.rs"

# 2022

[[bin]]
name = "2022-day1"
path = "src/2022/day1.rs"

[[bin]]
name = "2022-day2"
path = "src/2022/day2.rs"
