# general
edition = "2021"
version = "Two"
#required_version = "CARGO_PKG_VERSION"
unstable_features = true

# errors and meta
disable_all_formatting = false
error_on_line_overflow = false
error_on_unformatted = false
hide_parse_errors = false
ignore = []
report_fixme = "Always"
report_todo = "Always"
skip_children = false

# meta format
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = false
format_macro_bodies = true
format_strings = true

# indents
hard_tabs = true
tab_spaces = 4
newline_style = "Auto"
indent_style = "Block"

# braces and blank lines
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
#fn_params_layout = "Vertical" # should work but doesnt??
fn_args_layout = "Tall"
fn_single_line = true
force_multiline_blocks = false
inline_attribute_width = 0
overflow_delimited_expr = true
struct_lit_single_line = true
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1

# imports and modules
imports_granularity = "Module"
imports_indent = "Visual"
imports_layout = "Mixed"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
merge_derives = true

# match
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# comments
normalize_comments = false
normalize_doc_attributes = false
wrap_comments = true

# expressions
combine_control_expr = true
condense_wildcard_suffixes = true
empty_item_single_line = true
remove_nested_parens = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
trailing_comma = "Never"
trailing_semicolon = true
binop_separator = "Front"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
type_punctuation_density = "Wide"
hex_literal_case = "Preserve"

# heuristics
use_small_heuristics = "Default"
max_width = 160
array_width = 80
attr_fn_like_width = 80
chain_width = 120
comment_width = 120
fn_call_width = 80
single_line_if_else_max_width = 80
struct_lit_width = 18
struct_variant_width = 35

# unused
enum_discrim_align_threshold = 0
struct_field_align_threshold = 0
color = "Auto"
force_explicit_abi = true
license_template_path = ""
